version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  r2-d7:
    jobs:
      - run-tests


jobs:
  run-tests:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: pytest
          pkg-manager: pip
          pypi-cache: false
      - run:
          name: Run tests
          command: pytest
